spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

mybatis-plus:
  mapper-locations: classpath:/com/boot/mapper/xml/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  upload: C:\Users\clove\Desktop\boot\file\



